/**
 * Taskbar state mutation constants
 */
export const ADD_ITEM = 'ADD_ITEM'
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM'
export const RESET_ACTIVE_ITEM = 'RESET_ACTIVE_ITEM'
export const REMOVE_ITEM_AT_INDEX = 'REMOVE_ITEM_AT_INDEX'
export const SAVE_TASKBAR_ITEM_DATA = 'SAVE_TASKBAR_ITEM_DATA'
export const SAVE_TASKBAR_ITEM_FORM_DATA = 'SAVE_TASKBAR_ITEM_FORM_DATA'
