export const LOGIN = 'login'
export const REGISTER = 'register'
export const LOGOUT = 'logout'
export const OVERVIEW = 'overview'
export const CURRENCY = 'currency'

export const LIST_CLIENTS = 'clients'
export const LIST_PRODUCTS = 'products'
export const LIST_INVOICES = 'invoices'
export const LIST_PAYMENTS = 'payments'
export const LIST_RECURRING_INVOICES = 'recurring_invoices'
export const LIST_CREDITS = 'credits'
export const LIST_QUOTES = 'quotes'
export const LIST_EXPENSES = 'expenses'
export const LIST_VENDORS = 'vendors'
export const LIST_PROJECTS = 'projects'
