const state = {
  companySizes: [],
  countries: [],
  currencies: [],
  industries: [],
  languages: [],
  timezones: [],
  paymentTypes: [],
  paymentTerms: [
    { id: 7, name: '7 Days' },
    { id: 14, name: '14 Days' },
    { id: 15, name: '15 Days' },
    { id: 30, name: '30 Days' },
    { id: 60, name: '60 Days' },
    { id: 90, name: '90 Days' },
    { id: 0, name: '0 Days' }
  ],
  frequencies: [
    { name: 'weekly', value: 1, type: 'week' },
    { name: 'two_weeks', value: 2, type: 'week' },
    { name: 'four_weeks', value: 4, type: 'week' },
    { name: 'monthly', value: 1, type: 'month' },
    { name: 'two_months', value: 2, type: 'month' },
    { name: 'three_months', value: 3, type: 'month' },
    { name: 'six_months', value: 6, type: 'month' },
    { name: 'annually', value: 1, type: 'year' }
  ],
  member_states: [
    { 'code': 'AT', 'name': 'AT - Austria' },
    { 'code': 'BE', 'name': 'BE - Belgium' },
    { 'code': 'BG', 'name': 'BG - Bulgaria' },
    { 'code': 'CY', 'name': 'CY - Cyprus' },
    { 'code': 'CZ', 'name': 'CZ - Czech Republic' },
    { 'code': 'DE', 'name': 'DE - Germany' },
    { 'code': 'DK', 'name': 'DK - Denmark' },
    { 'code': 'EE', 'name': 'EE - Estonia' },
    { 'code': 'EL', 'name': 'EL - Greece' },
    { 'code': 'ES', 'name': 'ES - Spain' },
    { 'code': 'FI', 'name': 'FI - Finland' },
    { 'code': 'FR', 'name': 'FR - France ' },
    { 'code': 'GB', 'name': 'GB - United Kingdom' },
    { 'code': 'HR', 'name': 'HR - Croatia' },
    { 'code': 'HU', 'name': 'HU - Hungary' },
    { 'code': 'IE', 'name': 'IE - Ireland' },
    { 'code': 'IT', 'name': 'IT - Italy' },
    { 'code': 'LT', 'name': 'LT - Lithuania' },
    { 'code': 'LU', 'name': 'LU - Luxembourg' },
    { 'code': 'LV', 'name': 'LV - Latvia' },
    { 'code': 'MT', 'name': 'MT - Malta' },
    { 'code': 'NL', 'name': 'NL - The Netherlands' },
    { 'code': 'PL', 'name': 'PL - Poland' },
    { 'code': 'PT', 'name': 'PT - Portugal' },
    { 'code': 'RO', 'name': 'RO - Romania' },
    { 'code': 'SE', 'name': 'SE - Sweden' },
    { 'code': 'SI', 'name': 'SI - Slovenia' },
    { 'code': 'SK', 'name': 'SK - Slovakia' }
  ]
}

export default state
